apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zdyghzrko-go
  janus-idp.io/tekton: zdyghzrko-go
  backstage.io/kubernetes-id: zdyghzrko-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zdyghzrko-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
